# Generated by Django 5.2.7 on 2025-10-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=200)),
                ('text_field', models.TextField()),
                ('score', models.IntegerField()),
                ('skiped', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Players',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='integer_field',
            new_name='turn',
        ),
        migrations.AddField(
            model_name='game',
            name='gameEnd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='name', max_length=200),
        ),
    ]
